# Generated by Django 5.2.7 on 2025-12-18 15:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["name"],
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.CharField(
                default="Russia", max_length=100, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="city",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="City must contain only Latin letters, spaces and hyphens",
                        regex="^[a-zA-Z\\s\\-]+$",
                    )
                ],
                verbose_name="City name",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.CharField(blank=True, max_length=150, verbose_name="Region"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Supported formats: JPG, PNG, GIF, WebP. Maximum size: 5MB.",
                null=True,
                upload_to="profile_images/%Y/%m/%d/",
                validators=[
                    users.models.validate_image_extension,
                    users.models.validate_image_size,
                ],
                verbose_name="Profile avatar",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Maximum 500 characters",
                max_length=500,
                verbose_name="About me",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="Select city from list",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
