# Generated by Django 5.2.7 on 2025-12-18 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_city_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="City name can contain Latin letters (including German and French characters with accents), spaces, hyphens and apostrophes",
                        regex="^[a-zA-ZÀ-ÿÆæŒœß\\s\\-']+$",
                    )
                ],
                verbose_name="City name",
            ),
        ),
    ]
