# Generated by Django 5.2.7 on 2026-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_city_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Your name that will be visible to other users",
                max_length=100,
                verbose_name="First name",
            ),
        ),
    ]
