# Generated by Django 5.2.7 on 2025-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_order", "🎉 New order"),
                    ("order_status_changed", "📦 Order status changed"),
                    ("new_message", "💬 New message"),
                    ("product_favorited", "❤️ Product added to favorites"),
                    ("system", "🔔 System notification"),
                    ("order_cancelled", "❌ Order cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
