# Generated by Django 5.2.7 on 2025-12-18 15:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorite products",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                max_length=300,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Description must contain only Latin characters, numbers and punctuation",
                        regex="^[a-zA-Z0-9\\s\\-\\!\\.\\(\\)\\,\\:\\;]+$",
                    )
                ],
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_approved",
            field=models.BooleanField(
                default=False, verbose_name="Approved by moderator"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Master",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Price must be at least 1 ruble"
                    ),
                    django.core.validators.MaxValueValidator(
                        5000000, message="Price cannot exceed 5,000,000 rubles"
                    ),
                ],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                max_length=60,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Title must contain only Latin characters, numbers and spaces",
                        regex="^[a-zA-Z0-9\\s\\-\\!\\.\\(\\)]+$",
                    )
                ],
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product_images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Main image"),
        ),
    ]
