# Generated by Django 5.2.7 on 2026-01-08 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_options_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="category",
            name="language_code",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French"), ("de", "German")],
                default="en",
                max_length=10,
                verbose_name="Language Code",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="translation_group",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Translation Group",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="URL"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("translation_group", "language_code")},
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("language_code", "slug"), name="unique_slug_per_language"
            ),
        ),
    ]
